//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroSoapReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    public partial class O_USUARIO_CTY : object
    {
        
        private decimal ESTADOField;
        
        private decimal ID_ENTIDADField;
        
        private decimal ID_USUARIOField;
        
        private string NOMBRE_COMPLETOField;
        
        private string PERFILField;
        
        private decimal PERFIL_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ESTADO
        {
            get
            {
                return this.ESTADOField;
            }
            set
            {
                this.ESTADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ENTIDAD
        {
            get
            {
                return this.ID_ENTIDADField;
            }
            set
            {
                this.ID_ENTIDADField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_USUARIO
        {
            get
            {
                return this.ID_USUARIOField;
            }
            set
            {
                this.ID_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_COMPLETO
        {
            get
            {
                return this.NOMBRE_COMPLETOField;
            }
            set
            {
                this.NOMBRE_COMPLETOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERFIL
        {
            get
            {
                return this.PERFILField;
            }
            set
            {
                this.PERFILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PERFIL_ID
        {
            get
            {
                return this.PERFIL_IDField;
            }
            set
            {
                this.PERFIL_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_RESULTADO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    public partial class O_RESULTADO_CTY : object
    {
        
        private decimal ID_RESULTADOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_RESULTADO
        {
            get
            {
                return this.ID_RESULTADOField;
            }
            set
            {
                this.ID_RESULTADOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_DETALLE_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    public partial class O_DETALLE_USUARIO_CTY : object
    {
        
        private decimal AUD_ESTADOField;
        
        private string CLAVEField;
        
        private string COMPLEMENTOField;
        
        private string EMAILField;
        
        private decimal ENTIDAD_IDField;
        
        private decimal ESTADOField;
        
        private string EXPEDICIONField;
        
        private string EXPEDICION_ABREVIACIONField;
        
        private decimal EXPEDICION_IDField;
        
        private decimal FECHA_NACIMIENTOField;
        
        private string GENEROField;
        
        private decimal GENERO_IDField;
        
        private decimal ID_USUARIOField;
        
        private string LOGINField;
        
        private string NOMBREField;
        
        private string NUMERO_IDENTIFICACIONField;
        
        private decimal PERSONA_IDField;
        
        private string PRIMER_APELLIDOField;
        
        private string SEGUNDO_APELLIDOField;
        
        private string TIPO_IDENTIFICACIONField;
        
        private decimal TIPO_IDENTIFICACION_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AUD_ESTADO
        {
            get
            {
                return this.AUD_ESTADOField;
            }
            set
            {
                this.AUD_ESTADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLAVE
        {
            get
            {
                return this.CLAVEField;
            }
            set
            {
                this.CLAVEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPLEMENTO
        {
            get
            {
                return this.COMPLEMENTOField;
            }
            set
            {
                this.COMPLEMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL
        {
            get
            {
                return this.EMAILField;
            }
            set
            {
                this.EMAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ENTIDAD_ID
        {
            get
            {
                return this.ENTIDAD_IDField;
            }
            set
            {
                this.ENTIDAD_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ESTADO
        {
            get
            {
                return this.ESTADOField;
            }
            set
            {
                this.ESTADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPEDICION
        {
            get
            {
                return this.EXPEDICIONField;
            }
            set
            {
                this.EXPEDICIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPEDICION_ABREVIACION
        {
            get
            {
                return this.EXPEDICION_ABREVIACIONField;
            }
            set
            {
                this.EXPEDICION_ABREVIACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EXPEDICION_ID
        {
            get
            {
                return this.EXPEDICION_IDField;
            }
            set
            {
                this.EXPEDICION_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FECHA_NACIMIENTO
        {
            get
            {
                return this.FECHA_NACIMIENTOField;
            }
            set
            {
                this.FECHA_NACIMIENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GENERO
        {
            get
            {
                return this.GENEROField;
            }
            set
            {
                this.GENEROField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GENERO_ID
        {
            get
            {
                return this.GENERO_IDField;
            }
            set
            {
                this.GENERO_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_USUARIO
        {
            get
            {
                return this.ID_USUARIOField;
            }
            set
            {
                this.ID_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN
        {
            get
            {
                return this.LOGINField;
            }
            set
            {
                this.LOGINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE
        {
            get
            {
                return this.NOMBREField;
            }
            set
            {
                this.NOMBREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_IDENTIFICACION
        {
            get
            {
                return this.NUMERO_IDENTIFICACIONField;
            }
            set
            {
                this.NUMERO_IDENTIFICACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PERSONA_ID
        {
            get
            {
                return this.PERSONA_IDField;
            }
            set
            {
                this.PERSONA_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRIMER_APELLIDO
        {
            get
            {
                return this.PRIMER_APELLIDOField;
            }
            set
            {
                this.PRIMER_APELLIDOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEGUNDO_APELLIDO
        {
            get
            {
                return this.SEGUNDO_APELLIDOField;
            }
            set
            {
                this.SEGUNDO_APELLIDOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_IDENTIFICACION
        {
            get
            {
                return this.TIPO_IDENTIFICACIONField;
            }
            set
            {
                this.TIPO_IDENTIFICACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TIPO_IDENTIFICACION_ID
        {
            get
            {
                return this.TIPO_IDENTIFICACION_IDField;
            }
            set
            {
                this.TIPO_IDENTIFICACION_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_MODULOS_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    public partial class O_MODULOS_USUARIO_CTY : object
    {
        
        private string DESCRIPCIONField;
        
        private decimal ID_MODULOField;
        
        private string URLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION
        {
            get
            {
                return this.DESCRIPCIONField;
            }
            set
            {
                this.DESCRIPCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MODULO
        {
            get
            {
                return this.ID_MODULOField;
            }
            set
            {
                this.ID_MODULOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_PERFILES_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    public partial class O_PERFILES_USUARIO_CTY : object
    {
        
        private string DESCRIPCIONField;
        
        private decimal ESTADOField;
        
        private decimal ID_PERFILField;
        
        private decimal ID_PERFIL_PADREField;
        
        private decimal PRIORIDADField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION
        {
            get
            {
                return this.DESCRIPCIONField;
            }
            set
            {
                this.DESCRIPCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ESTADO
        {
            get
            {
                return this.ESTADOField;
            }
            set
            {
                this.ESTADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERFIL
        {
            get
            {
                return this.ID_PERFILField;
            }
            set
            {
                this.ID_PERFILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERFIL_PADRE
        {
            get
            {
                return this.ID_PERFIL_PADREField;
            }
            set
            {
                this.ID_PERFIL_PADREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRIORIDAD
        {
            get
            {
                return this.PRIORIDADField;
            }
            set
            {
                this.PRIORIDADField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_MENUS_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    public partial class O_MENUS_USUARIO_CTY : object
    {
        
        private string ABREVIACIONField;
        
        private string ENLACEField;
        
        private string ICONOField;
        
        private decimal ID_MENUField;
        
        private decimal ID_MENU_PADREField;
        
        private decimal ID_MODULOField;
        
        private decimal ORDENField;
        
        private decimal PRIORIDADField;
        
        private string TITULOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION
        {
            get
            {
                return this.ABREVIACIONField;
            }
            set
            {
                this.ABREVIACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENLACE
        {
            get
            {
                return this.ENLACEField;
            }
            set
            {
                this.ENLACEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ICONO
        {
            get
            {
                return this.ICONOField;
            }
            set
            {
                this.ICONOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MENU
        {
            get
            {
                return this.ID_MENUField;
            }
            set
            {
                this.ID_MENUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MENU_PADRE
        {
            get
            {
                return this.ID_MENU_PADREField;
            }
            set
            {
                this.ID_MENU_PADREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MODULO
        {
            get
            {
                return this.ID_MODULOField;
            }
            set
            {
                this.ID_MODULOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ORDEN
        {
            get
            {
                return this.ORDENField;
            }
            set
            {
                this.ORDENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRIORIDAD
        {
            get
            {
                return this.PRIORIDADField;
            }
            set
            {
                this.PRIORIDADField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITULO
        {
            get
            {
                return this.TITULOField;
            }
            set
            {
                this.TITULOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.anh.gob.bo:8443", ConfigurationName="HydroSoapReference.IServicioHydroSesion")]
    public interface IServicioHydroSesion
    {
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/Autenticar", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.AutenticarResponse> AutenticarAsync(HydroSoapReference.AutenticarRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarActDir", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarActDirResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.AutenticarActDirResponse> AutenticarActDirAsync(HydroSoapReference.AutenticarActDirRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ExisteUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ExisteUsuarioResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.ExisteUsuarioResponse> ExisteUsuarioAsync(HydroSoapReference.ExisteUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/RegistrarUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.RegistrarUsuarioResponse> RegistrarUsuarioAsync(HydroSoapReference.RegistrarUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ActivarUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ActivarUsuarioResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.ActivarUsuarioResponse> ActivarUsuarioAsync(HydroSoapReference.ActivarUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.ObtenerUsuarioResponse> ObtenerUsuarioAsync(HydroSoapReference.ObtenerUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerModulosUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerModulosUsuarioRespon" +
            "se")]
        System.Threading.Tasks.Task<HydroSoapReference.ObtenerModulosUsuarioResponse> ObtenerModulosUsuarioAsync(HydroSoapReference.ObtenerModulosUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObternerPerfilesUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObternerPerfilesUsuarioResp" +
            "onse")]
        System.Threading.Tasks.Task<HydroSoapReference.ObternerPerfilesUsuarioResponse> ObternerPerfilesUsuarioAsync(HydroSoapReference.ObternerPerfilesUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusUsuarioResponse" +
            "")]
        System.Threading.Tasks.Task<HydroSoapReference.ObtenerMenusUsuarioResponse> ObtenerMenusUsuarioAsync(HydroSoapReference.ObtenerMenusUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusPerfil", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusPerfilResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.ObtenerMenusPerfilResponse> ObtenerMenusPerfilAsync(HydroSoapReference.ObtenerMenusPerfilRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/CambiarClave", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/CambiarClaveResponse")]
        System.Threading.Tasks.Task<HydroSoapReference.CambiarClaveResponse> CambiarClaveAsync(HydroSoapReference.CambiarClaveRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarV2", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarV2Response")]
        System.Threading.Tasks.Task<HydroSoapReference.AutenticarV2Response> AutenticarV2Async(HydroSoapReference.AutenticarV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticar", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class AutenticarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public string strCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=3)]
        public string strMensajeError;
        
        public AutenticarRequest()
        {
        }
        
        public AutenticarRequest(string strCredencial, string strUsuario, string strClave, string strMensajeError)
        {
            this.strCredencial = strCredencial;
            this.strUsuario = strUsuario;
            this.strClave = strClave;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class AutenticarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_USUARIO_CTY AutenticarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strMensajeError;
        
        public AutenticarResponse()
        {
        }
        
        public AutenticarResponse(HydroSoapReference.O_USUARIO_CTY AutenticarResult, string strMensajeError)
        {
            this.AutenticarResult = AutenticarResult;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarActDir", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class AutenticarActDirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public string strCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strMensajeError;
        
        public AutenticarActDirRequest()
        {
        }
        
        public AutenticarActDirRequest(string strCredencial, string autenticacion, string strMensajeError)
        {
            this.strCredencial = strCredencial;
            this.autenticacion = autenticacion;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarActDirResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class AutenticarActDirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_USUARIO_CTY AutenticarActDirResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strMensajeError;
        
        public AutenticarActDirResponse()
        {
        }
        
        public AutenticarActDirResponse(HydroSoapReference.O_USUARIO_CTY AutenticarActDirResult, string strMensajeError)
        {
            this.AutenticarActDirResult = AutenticarActDirResult;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteUsuario", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ExisteUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public string strCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strMensajeError;
        
        public ExisteUsuarioRequest()
        {
        }
        
        public ExisteUsuarioRequest(string strCredencial, string strUsuario, string strMensajeError)
        {
            this.strCredencial = strCredencial;
            this.strUsuario = strUsuario;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteUsuarioResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ExisteUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_RESULTADO_CTY ExisteUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strMensajeError;
        
        public ExisteUsuarioResponse()
        {
        }
        
        public ExisteUsuarioResponse(HydroSoapReference.O_RESULTADO_CTY ExisteUsuarioResult, string strMensajeError)
        {
            this.ExisteUsuarioResult = ExisteUsuarioResult;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarUsuario", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class RegistrarUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public string strCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strMensajeError;
        
        public RegistrarUsuarioRequest()
        {
        }
        
        public RegistrarUsuarioRequest(string strCredencial, string strUsuario, string strMensajeError)
        {
            this.strCredencial = strCredencial;
            this.strUsuario = strUsuario;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarUsuarioResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class RegistrarUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_RESULTADO_CTY RegistrarUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strMensajeError;
        
        public RegistrarUsuarioResponse()
        {
        }
        
        public RegistrarUsuarioResponse(HydroSoapReference.O_RESULTADO_CTY RegistrarUsuarioResult, string strMensajeError)
        {
            this.RegistrarUsuarioResult = RegistrarUsuarioResult;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivarUsuario", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ActivarUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public string strCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public decimal decIdUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strMensajeError;
        
        public ActivarUsuarioRequest()
        {
        }
        
        public ActivarUsuarioRequest(string strCredencial, decimal decIdUsuario, string strMensajeError)
        {
            this.strCredencial = strCredencial;
            this.decIdUsuario = decIdUsuario;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivarUsuarioResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ActivarUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_RESULTADO_CTY ActivarUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strMensajeError;
        
        public ActivarUsuarioResponse()
        {
        }
        
        public ActivarUsuarioResponse(HydroSoapReference.O_RESULTADO_CTY ActivarUsuarioResult, string strMensajeError)
        {
            this.ActivarUsuarioResult = ActivarUsuarioResult;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuario", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public string strCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public decimal decIdUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strMensajeError;
        
        public ObtenerUsuarioRequest()
        {
        }
        
        public ObtenerUsuarioRequest(string strCredencial, decimal decIdUsuario, string strMensajeError)
        {
            this.strCredencial = strCredencial;
            this.decIdUsuario = decIdUsuario;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuarioResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_DETALLE_USUARIO_CTY ObtenerUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strMensajeError;
        
        public ObtenerUsuarioResponse()
        {
        }
        
        public ObtenerUsuarioResponse(HydroSoapReference.O_DETALLE_USUARIO_CTY ObtenerUsuarioResult, string strMensajeError)
        {
            this.ObtenerUsuarioResult = ObtenerUsuarioResult;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModulosUsuario", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerModulosUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public decimal decIdUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string credencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string mensajeError;
        
        public ObtenerModulosUsuarioRequest()
        {
        }
        
        public ObtenerModulosUsuarioRequest(decimal decIdUsuario, string credencial, string mensajeError)
        {
            this.decIdUsuario = decIdUsuario;
            this.credencial = credencial;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModulosUsuarioResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerModulosUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_MODULOS_USUARIO_CTY[] ObtenerModulosUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string mensajeError;
        
        public ObtenerModulosUsuarioResponse()
        {
        }
        
        public ObtenerModulosUsuarioResponse(HydroSoapReference.O_MODULOS_USUARIO_CTY[] ObtenerModulosUsuarioResult, string mensajeError)
        {
            this.ObtenerModulosUsuarioResult = ObtenerModulosUsuarioResult;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObternerPerfilesUsuario", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObternerPerfilesUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public decimal decIdUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public decimal decIdModulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string credencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=3)]
        public string mensajeError;
        
        public ObternerPerfilesUsuarioRequest()
        {
        }
        
        public ObternerPerfilesUsuarioRequest(decimal decIdUsuario, decimal decIdModulo, string credencial, string mensajeError)
        {
            this.decIdUsuario = decIdUsuario;
            this.decIdModulo = decIdModulo;
            this.credencial = credencial;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObternerPerfilesUsuarioResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObternerPerfilesUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_PERFILES_USUARIO_CTY[] ObternerPerfilesUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string mensajeError;
        
        public ObternerPerfilesUsuarioResponse()
        {
        }
        
        public ObternerPerfilesUsuarioResponse(HydroSoapReference.O_PERFILES_USUARIO_CTY[] ObternerPerfilesUsuarioResult, string mensajeError)
        {
            this.ObternerPerfilesUsuarioResult = ObternerPerfilesUsuarioResult;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerMenusUsuario", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerMenusUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public decimal decIdUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public decimal decIdModulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public decimal decIdPerfil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=3)]
        public string credencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=4)]
        public string mensajeError;
        
        public ObtenerMenusUsuarioRequest()
        {
        }
        
        public ObtenerMenusUsuarioRequest(decimal decIdUsuario, decimal decIdModulo, decimal decIdPerfil, string credencial, string mensajeError)
        {
            this.decIdUsuario = decIdUsuario;
            this.decIdModulo = decIdModulo;
            this.decIdPerfil = decIdPerfil;
            this.credencial = credencial;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerMenusUsuarioResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerMenusUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_MENUS_USUARIO_CTY[] ObtenerMenusUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string mensajeError;
        
        public ObtenerMenusUsuarioResponse()
        {
        }
        
        public ObtenerMenusUsuarioResponse(HydroSoapReference.O_MENUS_USUARIO_CTY[] ObtenerMenusUsuarioResult, string mensajeError)
        {
            this.ObtenerMenusUsuarioResult = ObtenerMenusUsuarioResult;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerMenusPerfil", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerMenusPerfilRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public decimal decIdPerfil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string credencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string mensajeError;
        
        public ObtenerMenusPerfilRequest()
        {
        }
        
        public ObtenerMenusPerfilRequest(decimal decIdPerfil, string credencial, string mensajeError)
        {
            this.decIdPerfil = decIdPerfil;
            this.credencial = credencial;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerMenusPerfilResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class ObtenerMenusPerfilResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_MENUS_USUARIO_CTY[] ObtenerMenusPerfilResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string mensajeError;
        
        public ObtenerMenusPerfilResponse()
        {
        }
        
        public ObtenerMenusPerfilResponse(HydroSoapReference.O_MENUS_USUARIO_CTY[] ObtenerMenusPerfilResult, string mensajeError)
        {
            this.ObtenerMenusPerfilResult = ObtenerMenusPerfilResult;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiarClave", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class CambiarClaveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public decimal decIdFiltro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public decimal decIdUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strClaveAnterior;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=3)]
        public string strClaveNueva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=4)]
        public string credencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=5)]
        public string mensajeError;
        
        public CambiarClaveRequest()
        {
        }
        
        public CambiarClaveRequest(decimal decIdFiltro, decimal decIdUsuario, string strClaveAnterior, string strClaveNueva, string credencial, string mensajeError)
        {
            this.decIdFiltro = decIdFiltro;
            this.decIdUsuario = decIdUsuario;
            this.strClaveAnterior = strClaveAnterior;
            this.strClaveNueva = strClaveNueva;
            this.credencial = credencial;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiarClaveResponse", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class CambiarClaveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_RESULTADO_CTY CambiarClaveResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string mensajeError;
        
        public CambiarClaveResponse()
        {
        }
        
        public CambiarClaveResponse(HydroSoapReference.O_RESULTADO_CTY CambiarClaveResult, string mensajeError)
        {
            this.CambiarClaveResult = CambiarClaveResult;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarV2", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class AutenticarV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public string strCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=2)]
        public string strClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=3)]
        public decimal decActualizarClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=4)]
        public decimal decIdModulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=5)]
        public string strMensajeError;
        
        public AutenticarV2Request()
        {
        }
        
        public AutenticarV2Request(string strCredencial, string strUsuario, string strClave, decimal decActualizarClave, decimal decIdModulo, string strMensajeError)
        {
            this.strCredencial = strCredencial;
            this.strUsuario = strUsuario;
            this.strClave = strClave;
            this.decActualizarClave = decActualizarClave;
            this.decIdModulo = decIdModulo;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarV2Response", WrapperNamespace="http://servicios.anh.gob.bo:8443", IsWrapped=true)]
    public partial class AutenticarV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=0)]
        public HydroSoapReference.O_USUARIO_CTY AutenticarV2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.anh.gob.bo:8443", Order=1)]
        public string strMensajeError;
        
        public AutenticarV2Response()
        {
        }
        
        public AutenticarV2Response(HydroSoapReference.O_USUARIO_CTY AutenticarV2Result, string strMensajeError)
        {
            this.AutenticarV2Result = AutenticarV2Result;
            this.strMensajeError = strMensajeError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioHydroSesionChannel : HydroSoapReference.IServicioHydroSesion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioHydroSesionClient : System.ServiceModel.ClientBase<HydroSoapReference.IServicioHydroSesion>, HydroSoapReference.IServicioHydroSesion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioHydroSesionClient() : 
                base(ServicioHydroSesionClient.GetDefaultBinding(), ServicioHydroSesionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HydroCoreSesionEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioHydroSesionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioHydroSesionClient.GetBindingForEndpoint(endpointConfiguration), ServicioHydroSesionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioHydroSesionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioHydroSesionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioHydroSesionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioHydroSesionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioHydroSesionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.AutenticarResponse> AutenticarAsync(HydroSoapReference.AutenticarRequest request)
        {
            return base.Channel.AutenticarAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.AutenticarActDirResponse> AutenticarActDirAsync(HydroSoapReference.AutenticarActDirRequest request)
        {
            return base.Channel.AutenticarActDirAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.ExisteUsuarioResponse> ExisteUsuarioAsync(HydroSoapReference.ExisteUsuarioRequest request)
        {
            return base.Channel.ExisteUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.RegistrarUsuarioResponse> RegistrarUsuarioAsync(HydroSoapReference.RegistrarUsuarioRequest request)
        {
            return base.Channel.RegistrarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.ActivarUsuarioResponse> ActivarUsuarioAsync(HydroSoapReference.ActivarUsuarioRequest request)
        {
            return base.Channel.ActivarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.ObtenerUsuarioResponse> ObtenerUsuarioAsync(HydroSoapReference.ObtenerUsuarioRequest request)
        {
            return base.Channel.ObtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.ObtenerModulosUsuarioResponse> ObtenerModulosUsuarioAsync(HydroSoapReference.ObtenerModulosUsuarioRequest request)
        {
            return base.Channel.ObtenerModulosUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.ObternerPerfilesUsuarioResponse> ObternerPerfilesUsuarioAsync(HydroSoapReference.ObternerPerfilesUsuarioRequest request)
        {
            return base.Channel.ObternerPerfilesUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.ObtenerMenusUsuarioResponse> ObtenerMenusUsuarioAsync(HydroSoapReference.ObtenerMenusUsuarioRequest request)
        {
            return base.Channel.ObtenerMenusUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.ObtenerMenusPerfilResponse> ObtenerMenusPerfilAsync(HydroSoapReference.ObtenerMenusPerfilRequest request)
        {
            return base.Channel.ObtenerMenusPerfilAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.CambiarClaveResponse> CambiarClaveAsync(HydroSoapReference.CambiarClaveRequest request)
        {
            return base.Channel.CambiarClaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<HydroSoapReference.AutenticarV2Response> AutenticarV2Async(HydroSoapReference.AutenticarV2Request request)
        {
            return base.Channel.AutenticarV2Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HydroCoreSesionEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HydroCoreSesionEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://vsrvuid006.anh.gob.bo:8443/WSCore/ServicioHydroSesion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioHydroSesionClient.GetBindingForEndpoint(EndpointConfiguration.HydroCoreSesionEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioHydroSesionClient.GetEndpointAddress(EndpointConfiguration.HydroCoreSesionEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            HydroCoreSesionEndPoint,
        }
    }
}
